// DiscForge — proprietary. Copyright (c) 2026 MaTRIX TeAm. All rights reserved.
// Not open source. No permission is granted to copy, fork or redistribute.
// See LICENSE at the root of this repository.

using System.Text;

namespace DiscForge.Core.Archive;

/// <summary>The kind of checksum sidecar file.</summary>
public enum SidecarKind { Sfv, Md5, Sha1 }

/// <summary>One name → checksum record from (or for) a sidecar file.</summary>
public sealed record HashLine(string Name, string Hash);

/// <summary>
/// Reads and writes the checksum sidecar files preservation tooling uses to guard a
/// folder against bit-rot: SFV (CRC-32, <c>name HEX</c>), and md5sum / sha1sum
/// (<c>hex *name</c>). Building and parsing are pure and testable; the actual file
/// re-hashing that a verify performs is driven by the caller.
/// </summary>
public static class HashSidecar
{
    /// <summary>An SFV file: a comment header then <c>name CRC32</c> (upper-case hex) per line.</summary>
    public static string BuildSfv(IEnumerable<HashLine> lines)
    {
        ArgumentNullException.ThrowIfNull(lines);
        var sb = new StringBuilder();
        sb.Append("; Generated by DiscForge\n");
        foreach (var l in lines)
            sb.Append(l.Name).Append(' ').Append(l.Hash.ToUpperInvariant()).Append('\n');
        return sb.ToString();
    }

    /// <summary>An md5sum / sha1sum file: <c>hex *name</c> per line (binary-mode asterisk).</summary>
    public static string BuildHashList(IEnumerable<HashLine> lines)
    {
        ArgumentNullException.ThrowIfNull(lines);
        var sb = new StringBuilder();
        foreach (var l in lines)
            sb.Append(l.Hash.ToLowerInvariant()).Append(" *").Append(l.Name).Append('\n');
        return sb.ToString();
    }

    public static string Build(SidecarKind kind, IEnumerable<HashLine> lines) =>
        kind == SidecarKind.Sfv ? BuildSfv(lines) : BuildHashList(lines);

    /// <summary>Parse a sidecar file's text into its name → hash records, skipping comments/blanks.</summary>
    public static IReadOnlyList<HashLine> Parse(SidecarKind kind, string text)
    {
        ArgumentNullException.ThrowIfNull(text);
        var result = new List<HashLine>();
        foreach (var raw in text.Split('\n'))
        {
            var line = raw.TrimEnd('\r').Trim();
            if (line.Length == 0 || line[0] is ';' or '#') continue;

            if (kind == SidecarKind.Sfv)
            {
                // "name possibly with spaces CRC32" — the hash is the last token.
                int sp = line.LastIndexOf(' ');
                if (sp <= 0 || sp == line.Length - 1) continue;
                result.Add(new HashLine(line[..sp].Trim(), line[(sp + 1)..].Trim().ToUpperInvariant()));
            }
            else
            {
                // "hex *name" or "hex  name" (md5sum/sha1sum).
                int sp = line.IndexOf(' ');
                if (sp <= 0) continue;
                string hash = line[..sp].Trim().ToLowerInvariant();
                string name = line[(sp + 1)..].TrimStart(' ', '*');
                result.Add(new HashLine(name, hash));
            }
        }
        return result;
    }

    /// <summary>The conventional extension for a sidecar kind (without the dot).</summary>
    public static string Extension(SidecarKind kind) => kind switch
    {
        SidecarKind.Sfv => "sfv",
        SidecarKind.Md5 => "md5",
        SidecarKind.Sha1 => "sha1",
        _ => "txt",
    };
}
